using HousePlanning.Core;

int passed = 0, failed = 0;
void Test(string name, Action body) { try { body(); Console.WriteLine("PASS " + name); passed++; } catch (Exception e) { Console.WriteLine("FAIL " + name + ": " + e.Message); failed++; } }
void Check(bool condition) { if (!condition) throw new Exception("Assertion failed"); }
void Reject(Action a) { try { a(); } catch (ArgumentException) { return; } throw new Exception("Expected validation error"); }
Test("Calibration maps known length and origin", () => { var b = new Blueprint(); b.Calibrate(new(10, 10), new(110, 10), 910); Check(Math.Abs(b.MmPerPixel - 9.1) < .00001); Check(b.ImageToWorld(new(110, 10)).DistanceTo(new(910, 0)) < .001); Reject(() => b.Calibrate(new(0, 0), new(0, 0), 100)); });
Test("Concave floor valid but bowtie rejected", () => { Geometry.ValidatePolygon([new(0, 0), new(4000, 0), new(4000, 2000), new(2000, 2000), new(2000, 4000), new(0, 4000)]); Reject(() => Geometry.ValidatePolygon([new(0, 0), new(2000, 2000), new(0, 2000), new(2000, 0)])); });
Test("Openings follow wall and reject overlap / overflow", () => { var h = House.CreateEmpty(); var w = new Element { Kind = Kind.Wall, A = new(0, 0), B = new(5000, 0) }; h.Elements.Add(w); var o = new Element { Kind = Kind.Window, HostId = w.Id, Offset = 1000, Width = 900, Height = 1000, Sill = 900 }; h.Elements.Add(o); h.Validate(); w.A = new(1000, 2000); w.B = new(6000, 2000); Check(h.OpeningCenter(o).DistanceTo(new(2450, 2000)) < .001); o.Offset = 4500; Reject(h.Validate); o.Offset = 1000; h.Elements.Add(new Element { Kind = Kind.Door, HostId = w.Id, Offset = 1200, Width = 800, Height = 2000 }); Reject(h.Validate); });
Test("Undo/redo and failed changes preserve state", () => { var s = new EditorSession(House.CreateEmpty()); s.Change(h => h.Name = "A"); s.Change(h => h.Name = "B"); s.Undo(); Check(s.House.Name == "A"); s.Redo(); Check(s.House.Name == "B"); Reject(() => s.Change(h => h.Elements.Add(new Element { Width = -1 }))); Check(s.House.Elements.Count == 0); });
Test("Wall deletion removes hosted openings", () => { var h = House.CreateEmpty(); var w = new Element { Kind = Kind.Wall }; h.Elements.Add(w); h.Elements.Add(new Element { Kind = Kind.Door, HostId = w.Id, Offset = 10, Width = 800, Height = 2000 }); h.Remove(w.Id); Check(h.Elements.Count == 0); });
Test("Archive embeds image and retains previous backup", () => { var dir = Path.Combine(Path.GetTempPath(), "house-test-" + Guid.NewGuid()); Directory.CreateDirectory(dir); try { var h = House.CreateEmpty(); h.Floors[0].Blueprint = new Blueprint { Image = [1, 2, 3, 4] }; var path = Path.Combine(dir, "a.houseplan"); HouseArchive.Save(h, path); h.Name = "changed"; HouseArchive.Save(h, path); var loaded = HouseArchive.Load(path); Check(loaded.Name == "changed"); Check(loaded.Floors[0].Blueprint!.Image.SequenceEqual(new byte[] { 1, 2, 3, 4 })); Check(HouseArchive.Load(path + ".bak").Name != "changed"); File.WriteAllText(path, "broken"); try { HouseArchive.Load(path); throw new Exception("accepted broken"); } catch (System.IO.InvalidDataException) { } } finally { Directory.Delete(dir, true); } });
Test("Sample validates and has two floors and void", () => { var h = SampleHouse.Create(); h.Validate(); Check(h.Floors.Count == 2); Check(h.Elements.Any(e => e.Kind == Kind.Void)); });
Test("Floor cutout preserves expected area", () => { List<Point> outer = [new(0, 0), new(10000, 0), new(10000, 8000), new(0, 8000)]; List<Point> hole = [new(6000, 4500), new(9400, 4500), new(9400, 7400), new(6000, 7400)]; var pieces = Geometry.Surface(outer, [hole]); double area = pieces.Sum(q => Math.Abs(q.Select((p, i) => p.X * q[(i + 1) % q.Length].Y - q[(i + 1) % q.Length].X * p.Y).Sum()) / 2); Check(Math.Abs(area - (80000000 - 3400 * 2900)) < .01); Check(pieces.All(q => !Geometry.Contains(q, new(8000, 6000)))); });
Test("Nonfinite and invalid floor rejected", () => { var h = House.CreateEmpty(); h.Floors[0].Storey = 2000; Reject(h.Validate); h.Floors[0].Storey = 2800; h.Elements.Add(new() { Height = double.NaN }); Reject(h.Validate); });
Test("Failed wall shrink does not change editor", () => { var h = House.CreateEmpty(); var w = new Element { Kind = Kind.Wall }; h.Elements.Add(w); h.Elements.Add(new() { Kind = Kind.Window, HostId = w.Id, Offset = 1500, Width = 1000, Height = 1000, Sill = 500 }); var s = new EditorSession(h); Reject(() => s.Change(x => x.Elements[0].B = new(2000, 0))); Check(s.House.Elements[0].B.X == 3000); });
Test("Crossing diagonal hole clips floor exactly", () => { List<Point> outer = [new(0, 0), new(10, 0), new(10, 10), new(0, 10)]; List<Point> hole = [new(-5, 5), new(5, -5), new(15, 5), new(5, 15)]; var pieces = Geometry.Surface(outer, [hole]); double area = pieces.Sum(q => Math.Abs(q.Select((p, i) => p.X * q[(i + 1) % q.Length].Y - q[(i + 1) % q.Length].X * p.Y).Sum()) / 2); Check(Math.Abs(area) < .001); });
Test("Boundary-crossing triangular hole removes clipped area", () => { List<Point> outer = [new(0, 0), new(10, 0), new(10, 10), new(0, 10)]; List<Point> hole = [new(-10, 2), new(20, 8), new(20, 12)]; var pieces = Geometry.Surface(outer, [hole]); double area = pieces.Sum(q => Math.Abs(q.Select((p, i) => p.X * q[(i + 1) % q.Length].Y - q[(i + 1) % q.Length].X * p.Y).Sum()) / 2); Check(Math.Abs(area - 80) < .001); });
Test("Diagonal intersections split at their X coordinates", () => { List<Point> outer = [new(0, 0), new(10, 0), new(10, 10), new(0, 10)]; List<Point> hole = [new(-5, -4), new(15, 6), new(15, 16)]; var pieces = Geometry.Surface(outer, [hole]); double area = pieces.Sum(q => Math.Abs(q.Select((p, i) => p.X * q[(i + 1) % q.Length].Y - q[(i + 1) % q.Length].X * p.Y).Sum()) / 2); Check(Math.Abs(area - 52.75) < .001); });
Console.WriteLine($"RESULT {passed} passed, {failed} failed");
return failed == 0 ? 0 : 1;
